version: '3.4'

services:
  frontend:
    image: frontend
    tty: true
    build:
      context: ./frontend/.devcontainer
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace:cached
    depends_on:
      - api
    ports:
      - "8000:8000"
    networks:
      - myNetwork

  api:
    image: api
    tty: true
    build:
      context: ./api/.devcontainer
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace:cached
    networks:
      - myNetwork

  redissever:
    image: redis
    volumes:
      - ./redis/redis-data:/data
    ports:
      - "6379:6379"
    command:
      # Save if 100 keys are added in every 10 seconds
      - "--save 10 100"
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge

